Repository FINALALT1/money-bridge, pull requests merged in 2023-06, with the labels that each got.

#6 Design: Layout 컴포넌트 크기 세팅
  src/app/globals.css
Labels: 🧑🏻‍🎨 UI

#9 Fix: layout 에서 children이 두번씩 출력되는 문제 해결
  src/app/layout.tsx
Labels: 🐛 bug

#10 Feat: TopNav 제작
  src/components/common/TopNav.tsx
Labels: 💫 feat

#11 Feat: ButtonModal 컴포넌트 기능 세팅
  src/app/layout.tsx
  src/components/Test.tsx
  src/components/common/ButtonModal.tsx
  src/types/common.ts
Labels: 💫 feat

#19 Conf: enum 작성
  src/components/common/BlurModal/index.tsx
  src/components/common/FixedButton/index.tsx
  src/components/common/PBCard/index.tsx
  src/components/common/PostCard/index.tsx
  src/constants/enum.ts
Labels: ⚙️ chore

#20 Docs: 상담예약 질문지, 투자성향 질문지 JSON 파일 작성
  src/constants/propensityCheckQuestions.json
  src/constants/reservationQuestions.json
Labels: 📝 docs

#24 Docs: mockup 데이터 세팅
  src/mocks/seon/analysisResult.json
  src/mocks/seon/faq.json
  src/mocks/seon/myQuestions.json
  src/mocks/seon/notice.json
  src/mocks/seon/pblist.json
  src/mocks/seon/reservationInfo.json
  src/mocks/seon/userInfo.json
  src/mocks/seon/userMyPage.json
  src/mocks/seon/userPblist.json
Labels: 📝 docs

#28 Feat: 공통 컴포넌트 구현
  public/assets/images/default_profile.png
  src/app/layout.tsx
  src/components/common/Navbar.tsx
  src/components/common/ReviewCardItem.tsx
  src/components/common/ReviewCardList.tsx
  src/types/common.ts
Labels: 💫 feat

#29 Docs: mockup 데이터 세팅
  src/constants/reviewMockData.json
Labels: 📝 docs

#30 #3 이슈에 대한 수정사항
  src/components/common/Button/FixedButton.tsx
  src/components/common/CardItem/PbCardItem.tsx
  src/components/common/CardItem/PostCardItem.tsx
  src/components/common/CardList/PbCardList.tsx
  src/components/common/CardList/PostCardList.tsx
Labels: 💫 feat

#35 Lounge 페이지
  src/app/Lounge.tsx
  src/app/page.tsx
  src/components/common/Card/CardItem/Card.tsx
  src/components/common/Card/CardItem/PbCardItem.tsx
  src/components/common/Card/CardItem/PostCardItem.tsx
  src/components/common/Card/CardList/PbCardList.tsx
  src/components/common/Card/CardList/PostCardList.tsx
  src/components/common/CardItem/PbCardItem.tsx
  src/components/common/CardItem/PostCardItem.tsx
  src/components/common/CardList/PbCardList.tsx
  src/components/common/Header/Header.tsx
  src/components/loungePage/Content.tsx
  src/components/loungePage/Intro.tsx
  src/components/loungePage/PbRecommend.tsx
  src/components/loungePage/Search.tsx
  src/mocks/hyeon17/Common/pbContent.json
Labels: 💫 feat

#42 입력을 2가지 받는 input component 제작
  package.json
  src/app/login/page.tsx
  src/components/common/DoubleInputForm.tsx
  src/components/loginPage/ButtonToFind.tsx
  src/components/loginPage/ButtonToSignUp.tsx
  src/components/loginPage/KeepLoginButton.tsx
  yarn.lock
Labels: 💫 feat

#44 아이디 찾기 페이지 제작
  src/app/findEmail/page.tsx
  src/app/findPassword/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/login/page.tsx
  src/components/common/DoubleInputForm.tsx
  src/components/common/LocationCard.tsx
  src/components/findEmailPage/InformationCheck.tsx
  src/types/DoubleInputForm.ts
Labels: 💫 feat

#46 Common components
  src/components/common/CardItem/ReviewCardItem.tsx
  src/components/common/CardItem/UserReservationItem.tsx
  src/components/common/CardList/ReviewCardList.tsx
  src/components/common/CardList/UserReservationList.tsx
  src/types/common.ts
Labels: 💫 feat

#47 고객관리 페이지 제작
  src/app/layout.tsx
  src/app/management/ConsultationStatus.tsx
  src/app/management/[slug]/page.tsx
  src/app/management/layout.tsx
  src/app/management/page.tsx
  src/components/common/CardItem/UserReservationItem.tsx
  src/components/common/CardList/UserReservationList.tsx
Labels: 💫 feat

#51 TopNav의 뒤로가기, 닫기 버튼 option 으로 변경
  src/components/common/TopNav.tsx
Labels: 💫 feat

#53 closePath 변수명을 path로 변경
  src/components/common/TopNav.tsx
Labels: 🐛 bug

#54 Bookmark 페이지 추가, 버그 수정
  src/app/bookmark/content.tsx
  src/app/bookmark/content/page.tsx
  src/app/bookmark/page.tsx
  src/app/bookmark/pb.tsx
  src/app/bookmark/pb/page.tsx
  src/app/globals.css
  src/app/lounge/page.tsx
  src/app/management/[slug]/page.tsx
  src/components/common/Card/CardItem/Card.tsx
  src/components/common/Card/CardItem/ContentCardItem.tsx
  src/components/common/Card/CardItem/PbCardItem.tsx
  src/components/common/Card/CardItem/ReviewCardItem.tsx
  src/components/common/Card/CardItem/UserReservationItem.tsx
  src/components/common/Card/CardList/ContentCardList.tsx
  src/components/common/Card/CardList/PbCardList.tsx
  src/components/common/Card/CardList/ReviewCardList.tsx
  src/components/common/Card/CardList/UserReservationList.tsx
  src/components/common/CardItem/PbCardItem.tsx
  src/components/common/CardItem/PostCardItem.tsx
  src/components/common/CardList/ContentCardList.tsx
  src/components/loungePage/Content.tsx
  src/components/loungePage/PbRecommend.tsx
  src/constants/enum.ts
  src/mocks/hyeon17/Lounge/all.json
  src/mocks/hyeon17/Lounge/newandhot.json
  src/mocks/hyeon17/PbDetail/same.json
  src/store/roleStore.ts
Labels: 🐛 bug, 💫 feat

#57 공통 컴포넌트 수정 및 이메일찾기 페이지 제작
  src/app/findEmail/page.tsx
  src/app/globals.css
  src/app/login/[slug]/page.tsx
  src/app/login/page.tsx
  src/components/common/DoubleInputForm.tsx
  src/components/common/TopNav.tsx
  src/components/findEmailPage/InformationCheck.tsx
  src/components/findEmailPage/SelectInformation.tsx
  src/components/loginPage/ButtonToAccountSetting.tsx
  src/components/loginPage/ButtonToFind.tsx
  src/components/loginPage/ButtonToSignUp.tsx
  src/components/loginPage/KeepLoginButton.tsx
Labels: 🐛 bug, 💫 feat

#58 Login page에 로그인 상태 유지하기 체크박스 추가
  public/assets/images/check.svg
  src/app/findEmail/page.tsx
  src/components/loginPage/KeepLoginButton.tsx
Labels: 💫 feat

#59 지도 컴포넌트에서 닫기버튼 삭제
  src/app/findPassword/page.tsx
  src/components/common/LocationCard.tsx
Labels: 💫 feat

#60 상담 예약 페이지 기능 구현
  src/app/globals.css
  src/app/reservation/complete/page.tsx
  src/app/reservation/page.tsx
  src/components/common/ButtonModal.tsx
  src/components/common/Modal/ModalBackground.tsx
  src/components/reservationPage/BubbleSection.tsx
  src/components/reservationPage/CandidateTime.tsx
  src/components/reservationPage/EditProfileModal.tsx
  src/components/reservationPage/ForwardingModal.tsx
  src/components/reservationPage/ModalLayout.tsx
  src/components/reservationPage/SelectCalendar.tsx
  src/components/reservationPage/SelectTimeModal.tsx
  src/components/reservationPage/TimeSelect.tsx
  src/constants/propensityCheckQuestions.json
  src/constants/reservationQuestions.json
  src/mocks/seon/reservationInfo.json
  src/store/reservationStore.ts
  src/styles/selectCalendar.css
  src/types/reservation.ts
  src/utils/convertAnswer.ts
Labels: 📝 docs, 💫 feat

#67 캐러셀, pb상세페이지
  package.json
  src/app/bookmark/page.tsx
  src/app/detail/content/page.tsx
  src/app/detail/edit/page.tsx
  src/app/detail/page.tsx
  src/app/detail/reviews/page.tsx
  src/app/globals.css
  src/components/common/Button/FixedButton.tsx
  src/components/common/Carousel/MainCarousel.tsx
  src/components/common/Modal/BlurModal.tsx
  src/components/loungePage/Content.tsx
  src/components/pbdetailPage/About.tsx
  src/components/pbdetailPage/Content.tsx
  src/components/pbdetailPage/Intro.tsx
  src/constants/enum.ts
  src/mocks/hyeon17/PbDetail/Profile/authProfile.json
  src/mocks/hyeon17/PbDetail/Profile/profile.json
  src/mocks/hyeon17/PbDetail/Review/pbreview.json
  src/mocks/hyeon17/PbDetail/boards.json
  src/mocks/hyeon17/PbDetail/profile.json
  src/styles/carousel.css
  src/styles/defaultCarousel.css
  yarn.lock
Labels: 💫 feat

#69 Topnav 구조 변경, 이미지 추가, backgroundColor props 추가
  public/assets/images/arrayBack.svg
  public/assets/images/close.svg
  src/app/findEmail/page.tsx
  src/app/findPassword/page.tsx
  src/app/login/[slug]/page.tsx
  src/components/common/TopNav.tsx
Labels: 💫 feat

#72 상담 예약 페이지 스타일링
  src/app/globals.css
  src/app/reservation/page.tsx
  src/components/reservationPage/BubbleSection.tsx
  src/components/reservationPage/EditProfileModal.tsx
  src/components/reservationPage/ForwardingModal.tsx
  src/components/reservationPage/ModalLayout.tsx
  src/components/reservationPage/SelectTimeModal.tsx
  src/components/reservationPage/TimeSelect.tsx
  tailwind.config.js
Labels: 🧑🏻‍🎨 UI, ⚙️ chore

#73 Pb상세, 수정,리뷰 페이지, 카카오톡 공유, 주소복사 커스텀 훅
  src/app/detail/page.tsx
  src/app/detail/review/page.tsx
  src/app/detail/reviews/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/components/pbdetailPage/About.tsx
  src/components/pbdetailPage/Content.tsx
  src/components/pbdetailPage/Intro.tsx
  src/components/pbdetailPage/pbreviewPage/PbReviewItem.tsx
  src/components/pbdetailPage/pbreviewPage/PbReviewList.tsx
  src/constants/enum.ts
  src/hooks/useCopyClipboard.ts
  src/mocks/hyeon17/PbDetail/Profile/authProfile.json
  src/mocks/hyeon17/PbDetail/Review/pbrecentreview.json
  src/mocks/hyeon17/PbDetail/Review/pbreview.json
  src/utils/shareKakao.ts
Labels: 💫 feat

#74 비밀번호 찾기 페이지 제작
  public/assets/images/help.svg
  src/app/findEmail/page.tsx
  src/app/findPassword/[...slug]/page.tsx
  src/app/findPassword/page.tsx
  src/app/login/[slug]/page.tsx
  src/app/login/page.tsx
  src/components/common/DoubleInputForm.tsx
  src/components/common/ResetPasswordForm.tsx
  src/components/findEmailPage/InformationCheck.tsx
  src/components/findPasswordPage/Authentication.tsx
  src/components/findPasswordPage/EnterInformation.tsx
  src/components/findPasswordPage/ResetPassword.tsx
  src/components/findPasswordPage/SelectInformation.tsx
  src/components/loginPage/ButtonToAccountSetting.tsx
  src/constants/enum.ts
Labels: 💫 feat, 🧑🏻‍🎨 UI

#76 상담 예약 페이지 버그 수정 및 main 태그 스타일링
  src/app/analysis/page.tsx
  src/app/globals.css
  src/app/reservation/page.tsx
  src/components/common/Navbar.tsx
  src/components/reservationPage/SelectCalendar.tsx
  src/components/reservationPage/SelectTimeModal.tsx
  src/types/reservation.ts
Labels: 🐛 bug, 🧑🏻‍🎨 UI

#79 일정관리 페이지 구현 완료
  package-lock.json
  public/assets/images/question_mark.svg
  src/app/schedule/Calendar.tsx
  src/app/schedule/ConsultationTimeCard.tsx
  src/app/schedule/DayScheduleList.tsx
  src/app/schedule/InfoModal.tsx
  src/app/schedule/page.tsx
  src/mocks/kjun/calendarData.json
  src/mocks/kjun/consultTime.json
  src/mocks/kjun/reviewMockData.json
  src/styles/calendar.css
  src/types/schedule.ts
  yarn.lock
Labels: 💫 feat, 🧑🏻‍🎨 UI, 🟦 typescript

#78 관리자 로그인 인증 페이지 제작 및 기타 컴포넌트 스타일 수정
  src/app/login/[slug]/page.tsx
  src/components/common/LocationCard.tsx
  src/components/common/TopNav.tsx
  src/components/findPasswordPage/Authentication.tsx
  src/components/loginPage/AdminAuthentication.tsx
Labels: 💫 feat, 🧑🏻‍🎨 UI

#81 navbar 컴포넌트 UI, 코드 수정
  public/assets/images/counselingStyle/DIRECTIONAL.svg
  public/assets/images/counselingStyle/EXPERIENCED.svg
  public/assets/images/counselingStyle/FAST.svg
  public/assets/images/counselingStyle/HONEST.svg
  public/assets/images/counselingStyle/KIND.svg
  public/assets/images/counselingStyle/METICULOUS.svg
  public/assets/images/counselingStyle/PRAGMATIC.svg
  public/assets/images/counselingStyle/PROFESSIONAL.svg
  public/assets/images/navbar/contacts.svg
  public/assets/images/navbar/home.svg
  public/assets/images/navbar/identity.svg
  public/assets/images/navbar/list.svg
  public/assets/images/specialty/BOND.svg
  public/assets/images/specialty/DERIVATIVE.svg
  public/assets/images/specialty/ETF.svg
  public/assets/images/specialty/FUND.svg
  public/assets/images/specialty/KOREAN_STOCK.svg
  public/assets/images/specialty/REAL_ESTATE.svg
  public/assets/images/specialty/US_STOCK.svg
  public/assets/images/specialty/WRAP.svg
  src/components/common/Navbar.tsx
Labels: 💫 feat, 🧑🏻‍🎨 UI, 🟦 typescript

#86 고객관리 페이지 로직 수정 및 스타일링 작업
  public/assets/images/default_profile.png
  public/assets/images/profile.svg
  src/app/management/ConsultationStatus.tsx
  src/app/management/[slug]/page.tsx
  src/app/management/layout.tsx
  src/app/management/page.tsx
  src/components/common/Card/CardItem/UserReservationItem.tsx
  src/components/common/Card/CardList/UserReservationList.tsx
  src/components/common/ProcessList.tsx
  src/mocks/kjun/managementRevervationStatue.json
Labels: 💫 feat, 🧑🏻‍🎨 UI, 🟦 typescript

#87 카카오톡 공유기능, 북마크, 공유 기능 커스텀 훅 제작, 캐러셀 스타일 수정, 콘텐츠 페이지 컴포넌트 구조 추가
  src/app/contents/[slug]/page.tsx
  src/app/contents/edit/page.tsx
  src/app/contents/temporary/page.tsx
  src/app/contents/write/page.tsx
  src/app/layout.tsx
  src/app/lounge/page.tsx
  src/app/lounge/search/page.tsx
  src/components/common/Carousel/MainCarousel.tsx
  src/components/contentsPage/Comments.tsx
  src/components/contentsPage/Content.tsx
  src/components/contentsPage/Poster.tsx
  src/components/contentsPage/TemporaryPage/TemporaryItem.tsx
  src/components/contentsPage/TemporaryPage/TemporaryList.tsx
  src/components/contentsPage/WritePage/Write.tsx
  src/components/loungePage/Intro.tsx
  src/components/loungePage/Search.tsx
  src/components/loungePage/SearchPage/ContentsItem.tsx
  src/components/loungePage/SearchPage/ContentsList.tsx
  src/components/loungePage/SearchPage/PbItem.tsx
  src/components/loungePage/SearchPage/PbList.tsx
  src/components/loungePage/SearchPage/SearchFilter.tsx
  src/components/pbdetailPage/About.tsx
  src/components/pbdetailPage/Intro.tsx
  src/constants/enum.ts
  src/hooks/useBookMark.ts
  src/hooks/useShare.ts
  src/styles/carousel.css
  src/utils/shareKakao.ts
Labels: 💫 feat

#88 나의 상담 페이지 구현 및 스타일링
  src/app/myCounseling/UserConsultationStatus.tsx
  src/app/myCounseling/page.tsx
  src/components/common/ProcessList.tsx
Labels: 💫 feat, 🧑🏻‍🎨 UI, 🟦 typescript

#91 ButtonModal 스타일링 및 props 추가
  src/app/globals.css
  src/app/page.tsx
  src/components/common/ButtonModal.tsx
  src/types/common.ts
Labels: 💫 feat, 🧑🏻‍🎨 UI

#92 tailwind 사용 시, px사용 부분 수정
  public/assets/images/arrayBack.svg
  src/app/findEmail/page.tsx
  src/app/findPassword/[...slug]/page.tsx
  src/app/globals.css
  src/app/login/[slug]/page.tsx
  src/app/login/page.tsx
  src/components/common/DoubleInputForm.tsx
  src/components/common/ResetPasswordForm.tsx
  src/components/common/TopNav.tsx
  src/components/findEmailPage/InformationCheck.tsx
  src/components/findPasswordPage/Authentication.tsx
  src/components/findPasswordPage/EnterInformation.tsx
  src/components/findPasswordPage/ResetPassword.tsx
  src/components/findPasswordPage/SelectInformation.tsx
  src/components/loginPage/AdminAuthentication.tsx
  src/components/loginPage/ButtonToAccountSetting.tsx
  src/components/loginPage/KeepLoginButton.tsx
Labels: ♻️ refactor

#93 라운지 UI 추가, 캐러셀 드래그, roleStore 수정, 아이콘 추가
  public/assets/images/icon/lounge_bookmark.svg
  public/assets/images/icon/lounge_mylist.svg
  public/assets/images/icon/lounge_search.svg
  public/assets/images/icon/lounge_write.svg
  public/assets/images/icon/pbcontent_bookmark.svg
  public/assets/images/icon/pbcontent_bookmark_filled.svg
  src/app/detail/page.tsx
  src/app/globals.css
  src/app/lounge/page.tsx
  src/components/common/Card/CardItem/ContentCardItem.tsx
  src/components/common/Card/CardList/ContentCardList.tsx
  src/components/common/Carousel/MainCarousel.tsx
  src/components/common/Header/Header.tsx
  src/components/loungePage/Content.tsx
  src/components/loungePage/Intro.tsx
  src/components/loungePage/PbRecommend.tsx
  src/components/pbdetailPage/About.tsx
  src/components/pbdetailPage/Content.tsx
  src/components/pbdetailPage/Intro.tsx
  src/store/roleStore.ts
  src/styles/carousel.css
  src/styles/lounge.css
Labels: 💫 feat, 🧑🏻‍🎨 UI

#95 일반 유저 회원가입 구현
  package.json
  public/assets/images/checkProvision.svg
  public/assets/images/openProvision.svg
  public/assets/images/uncheckProvision.svg
  src/app/apis/axios.ts
  src/app/apis/services/auth.ts
  src/app/findPassword/[...slug]/page.tsx
  src/app/globals.css
  src/app/join/[...slug]/page.tsx
  src/app/join/page.tsx
  src/app/login/page.tsx
  src/components/common/DoubleInputForm.tsx
  src/components/common/TopNav.tsx
  src/components/findPasswordPage/Authentication.tsx
  src/components/joinPage/common/AgreeProvision.tsx
  src/components/joinPage/common/JoinInformation.tsx
  src/components/joinPage/common/SetPasswordForm.tsx
  src/components/joinPage/user/UserComplete.tsx
  src/components/loginPage/AdminAuthentication.tsx
  src/components/loginPage/ButtonToAccountSetting.tsx
  src/constants/enum.ts
  src/hooks/useAuthentication.ts
  src/hooks/useJoin.ts
  src/hooks/useLogin.ts
  src/store/authenticationStore.ts
  src/store/joinStore.ts
  src/types/join.ts
  src/utils/cookies.ts
  yarn.lock
Labels: 💫 feat, 🧑🏻‍🎨 UI, 🟦 typescript

#96 Pb리스트 페이지 로직 구현 및 스타일링
  public/assets/images/arrayNext.svg
  src/app/globals.css
  src/app/my/layout.tsx
  src/app/my/page.tsx
  src/app/pblist/page.tsx
  src/app/pblist/recommend/page.tsx
  src/components/common/CompanyList.tsx
  src/components/pblistPage/PBMenu.tsx
  src/components/pblistPage/PropensityCard.tsx
  src/components/pblistPage/SortTab.tsx
  src/components/pblistPage/SpecialityList.tsx
  src/constants/enum.ts
  src/constants/pbListMenu.ts
  src/constants/propensityList.json
  src/hooks/usePBListQueries.ts
  src/mocks/seon/companyList.ts
  src/mocks/seon/pblist.json
  src/mocks/seon/userPblist.json
  src/styles/carousel.css
  src/styles/companyCarousel.css
  src/types/pblist.ts
  src/utils/chunkArray.ts
  src/utils/createQueryString.ts
  tailwind.config.js
Labels: 💫 feat, 🧑🏻‍🎨 UI, 🟦 typescript

#100 투자자 마이페이지, PB 마이페이지 로직 구현
  public/assets/images/nextIcon.svg
  public/assets/images/progressList/doneBoardBookMark.svg
  public/assets/images/progressList/donePropensity.svg
  public/assets/images/progressList/doneReservation.svg
  public/assets/images/progressList/doneReview.svg
  public/assets/images/progressList/hasDoneBoardBookMark.svg
  public/assets/images/progressList/hasDonePropensity.svg
  public/assets/images/progressList/hasDoneReservation.svg
  public/assets/images/progressList/hasDoneReview.svg
  src/app/layout.tsx
  src/app/my/layout.tsx
  src/app/my/page.tsx
  src/components/myPage/BookmarkPreview.tsx
  src/components/myPage/BookmarkPreviewCard.tsx
  src/components/myPage/MyReservationStatus.tsx
  src/components/myPage/PBInfo.tsx
  src/components/myPage/StepProgress.tsx
  src/components/myPage/UserInfo.tsx
  src/components/pblistPage/SpecialityList.tsx
  src/constants/stepProgressList.ts
  src/mocks/seon/pbMy.json
  src/mocks/seon/userMy.json
  src/types/my.ts
  src/types/pblist.ts
Labels: 💫 feat, 🧑🏻‍🎨 UI, 🟦 typescript

#101 유저 마이페이지 상세페이지 로직 구현
  package.json
  src/app/globals.css
  src/app/my/propensity/page.tsx
  src/components/myPage/propensityPage/PropensityChart.tsx
  src/components/myPage/propensityPage/PropensityInfoCard.tsx
  src/components/myPage/propensityPage/RecommendPBList.tsx
  src/components/myPage/propensityPage/RiskGrades.tsx
  src/components/pblistPage/PropensityCard.tsx
  src/constants/propensityList.json
  src/constants/propensityList.ts
  src/mocks/seon/propensityPage.json
  src/types/my.ts
  src/types/pblist.ts
  yarn.lock
Labels: 💫 feat, 🟦 typescript

#102 라운지 페이지 UI 작업
  public/assets/images/icon/share.svg
  src/app/bookmark/content/page.tsx
  src/app/bookmark/page.tsx
  src/app/bookmark/pb/page.tsx
  src/app/detail/content/page.tsx
  src/app/detail/edit/page.tsx
  src/app/detail/info/page.tsx
  src/app/globals.css
  src/app/lounge/page.tsx
  src/components/bookmarkPage/BookMark.tsx
  src/components/common/Card/CardItem/ContentCardItem.tsx
  src/components/common/Card/CardItem/PbCardItem.tsx
  src/components/common/Card/CardList/ContentCardList.tsx
  src/components/common/Card/CardList/PbCardList.tsx
  src/components/common/Carousel/MainCarousel.tsx
  src/components/loungePage/Content.tsx
  src/components/loungePage/Intro.tsx
  src/components/pbdetailPage/About.tsx
  src/components/pbdetailPage/Content.tsx
  src/components/pbdetailPage/Edit.tsx
  src/components/pbdetailPage/FixedButton.tsx
  src/components/pbdetailPage/Intro.tsx
  src/components/pbdetailPage/PbContentButton.tsx
  src/mocks/hyeon17/BookMark/content.json
  src/mocks/hyeon17/BookMark/pb.json
  src/mocks/hyeon17/Common/pbContent.json
  src/mocks/hyeon17/Common/pbList.json
  src/mocks/hyeon17/ContentDetail/board.json
  src/mocks/hyeon17/Lounge/all.json
  src/mocks/hyeon17/Lounge/hot.json
  src/mocks/hyeon17/Lounge/newandhot.json
  src/mocks/hyeon17/Lounge/search.json
  src/mocks/hyeon17/PbDetail/Profile/profile.json
  src/mocks/hyeon17/PbDetail/boards.json
  src/mocks/hyeon17/PbDetail/same.json
  src/store/roleStore.ts
  src/styles/carousel.css
  src/styles/lounge.css
  src/styles/pb.css
  tailwind.config.js
Labels: 💫 feat, 🧑🏻‍🎨 UI

#103 고객관리 -> 신규예약, 확정된 예약, 예약변경, 완료된 상담, 취소된 상담 페이지 스타일링 및 로직 구현
  public/assets/images/bottomArrow.svg
  src/app/globals.css
  src/app/management/canceledConsultation/[slug]/page.tsx
  src/app/management/canceledConsultation/page.tsx
  src/app/management/changeReservation/[slug]/page.tsx
  src/app/management/changeReservation/page.tsx
  src/app/management/completedConsultation/[slug]/page.tsx
  src/app/management/completedConsultation/page.tsx
  src/app/management/confirmedReservation/[slug]/page.tsx
  src/app/management/confirmedReservation/page.tsx
  src/app/management/newReservation/[slug]/page.tsx
  src/app/management/newReservation/page.tsx
  src/app/management/page.tsx
  src/app/myCounseling/page.tsx
  src/components/common/Card/CardItem/UserReservationItem.tsx
  src/components/common/ConsultationLocationSection.tsx
  src/components/common/ConsultationNoteSection.tsx
  src/components/common/ConsultationScheduleSection.tsx
  src/components/common/ConsultingHistoryCard.tsx
  src/components/common/DoubleButton.tsx
  src/components/common/LocationCopyButton.tsx
  src/components/common/SingleButton.tsx
  src/components/managementPage/ConsultationStatus.tsx
  src/components/managementPage/changeReservationPage/CalendarModal.tsx
  src/components/managementPage/changeReservationPage/CounselingModal.tsx
  src/components/managementPage/changeReservationPage/ScheduleSection.tsx
  src/components/managementPage/changeReservationPage/TimeModal.tsx
  src/mocks/kjun/managementReservations.json
  src/types/management.ts
Labels: 📝 docs, 💫 feat, 🧑🏻‍🎨 UI, 🟦 typescript

#104 마이페이지 세부페이지 공통영역 레이아웃 및 로직 구현
  src/app/globals.css
  src/app/layout.tsx
  src/app/my/editInfo/[slug]/page.tsx
  src/app/my/editInfo/page.tsx
  src/app/my/page.tsx
  src/app/my/propensity/page.tsx
  src/app/my/terms/page.tsx
  src/app/pblist/recommend/page.tsx
  src/app/secession/page.tsx
  src/components/common/ButtonModal.tsx
  src/components/findPasswordPage/Authentication.tsx
  src/components/myPage/MyReservationStatus.tsx
  src/components/myPage/PBInfo.tsx
  src/components/myPage/editInfoPage/CheckPassword.tsx
  src/components/myPage/editInfoPage/CheckUserEmail.tsx
  src/components/myPage/editInfoPage/EditInfoForm.tsx
  src/components/myPage/editInfoPage/EditPasswordForm.tsx
  src/components/myPage/editInfoPage/UserInfoList.tsx
  src/components/pblistPage/PropensityCard.tsx
  src/types/my.ts
  tailwind.config.js
Labels: 💫 feat, 🧑🏻‍🎨 UI, 🟦 typescript

#105 마이페이지 공지사항, FAQ 페이지 로직 구현
  public/assets/images/arrowDown.svg
  src/app/globals.css
  src/app/my/faq/page.tsx
  src/app/my/notice/page.tsx
  src/components/myPage/serviceCenterPage/AccordianItem.tsx
  src/components/myPage/serviceCenterPage/AccrodianList.tsx
  src/mocks/seon/faq.json
  src/mocks/seon/myQuestions.json
  src/mocks/seon/notice.json
  src/mocks/seon/pblist.json
  src/mocks/seon/userPblist.json
  src/types/my.ts
Labels: 💫 feat, 🧑🏻‍🎨 UI, 🟦 typescript

#109 아이디 찾기 API 구현
  src/app/apis/axios.ts
  src/app/apis/services/auth.ts
  src/app/findEmail/[...slug]/page.tsx
  src/app/findEmail/page.tsx
  src/components/common/DoubleInputForm.tsx
  src/components/findEmailPage/EnterInformation.tsx
  src/components/findEmailPage/InformationCheck.tsx
  src/components/findEmailPage/InformationItem.tsx
  src/components/findPasswordPage/SelectInformation.tsx
  src/components/joinPage/common/JoinInformation.tsx
  src/components/loginPage/ButtonToAccountSetting.tsx
  src/hooks/useFindEmail.ts
  src/hooks/useLogin.ts
  src/types/login.ts
  src/utils/cookies.ts
Labels: 💫 feat, 🟦 typescript

#112 고객관리 -> 예약변경 페이지 로직 추가 구현
  next.config.js
  src/app/globals.css
  src/app/management/canceledConsultation/[slug]/page.tsx
  src/app/management/canceledConsultation/page.tsx
  src/app/management/changeReservation/[slug]/page.tsx
  src/app/management/changeReservation/page.tsx
  src/app/management/completedConsultation/[slug]/page.tsx
  src/app/management/completedConsultation/page.tsx
  src/app/management/confirmedReservation/[slug]/page.tsx
  src/app/management/confirmedReservation/page.tsx
  src/app/management/newReservation/[slug]/page.tsx
  src/app/management/newReservation/page.tsx
  src/app/management/page.tsx
  src/app/myCounseling/page.tsx
  src/components/common/Card/CardItem/UserReservationItem.tsx
  src/components/managementPage/changeReservationPage/CounselingModal.tsx
  src/components/managementPage/changeReservationPage/LocationChangeModal.tsx
  src/types/management.ts
Labels: 💫 feat, 🧑🏻‍🎨 UI, 🟦 typescript

#113 투자자 나의상담 -> 신규예약, 완료된 예약, 취소된 상담, 후기 작성, 나의 후기 페이지 스타일링 및 로직 구현
  src/app/globals.css
  src/app/myCounseling/canceledConsultation/[slug]/page.tsx
  src/app/myCounseling/completedConsultation/[slug]/page.tsx
  src/app/myCounseling/myReview/[slug]/page.tsx
  src/app/myCounseling/newReservation/[slug]/page.tsx
  src/app/myCounseling/page.tsx
  src/app/myCounseling/reviewWrite/[slug]/page.tsx
Labels: 💫 feat, 🧑🏻‍🎨 UI, 🟦 typescript

#114 로그인한 유저 store에 정보 저장 및 비밀번호 찾기 API 구현
  src/app/apis/axios.ts
  src/app/apis/services/auth.ts
  src/app/detail/content/page.tsx
  src/app/detail/info/page.tsx
  src/app/join/[...slug]/page.tsx
  src/app/lounge/page.tsx
  src/components/common/Card/CardItem/ContentCardItem.tsx
  src/components/common/Card/CardItem/PbCardItem.tsx
  src/components/common/DoubleInputForm.tsx
  src/components/common/ResetPasswordForm.tsx
  src/components/findPasswordPage/Authentication.tsx
  src/components/findPasswordPage/SelectInformation.tsx
  src/hooks/useAuthentication.ts
  src/hooks/useLogin.ts
  src/hooks/usePasswordAuthentication.ts
  src/hooks/useResetPassword.ts
  src/store/roleStore.ts
  src/store/userStore.ts
  src/types/login.ts
Labels: 💫 feat, 🟦 typescript

#115 일정관리 -> 상담 가능 시간 변경 페이지
  public/assets/images/selectArrow.svg
  src/app/myCounseling/page.tsx
  src/app/schedule/changeConsultationTime/page.tsx
  src/app/schedule/page.tsx
  src/components/schedulePage/Calendar.tsx
  src/components/schedulePage/ConsultationTimeCard.tsx
  src/components/schedulePage/DayScheduleList.tsx
  src/components/schedulePage/InfoModal.tsx
  src/components/schedulePage/changeConsultationTimePage/TimePickerButton.tsx
Labels: 💫 feat, 🧑🏻‍🎨 UI, 🟦 typescript

#119 마이페이지 API 연결 작업
  next.config.js
  package.json
  src/app/apis/axios.ts
  src/app/apis/services/auth.ts
  src/app/apis/services/etc.ts
  src/app/apis/services/pb.ts
  src/app/apis/services/user.ts
  src/app/my/editInfo/[slug]/page.tsx
  src/app/my/editInfo/page.tsx
  src/app/my/faq/page.tsx
  src/app/my/notice/page.tsx
  src/app/my/page.tsx
  src/app/my/propensity/page.tsx
  src/app/withdraw/page.tsx
  src/components/common/Card/CardItem/PbCardItem.tsx
  src/components/myPage/BookmarkPreview.tsx
  src/components/myPage/BookmarkPreviewCard.tsx
  src/components/myPage/PBInfo.tsx
  src/components/myPage/UserInfo.tsx
  src/components/myPage/editInfoPage/CheckPassword.tsx
  src/components/myPage/editInfoPage/EditInfoForm.tsx
  src/components/myPage/editInfoPage/EditPasswordForm.tsx
  src/components/myPage/editInfoPage/UserInfoList.tsx
  src/components/myPage/propensityPage/PropensityChart.tsx
  src/components/myPage/serviceCenterPage/AccordianList.tsx
  src/components/myPage/serviceCenterPage/AccrodianList.tsx
  src/constants/propensityList.ts
  src/hooks/useCheckPassword.ts
  src/hooks/useLogout.ts
  src/hooks/useWithdraw.ts
  src/types/common.ts
  src/types/my.ts
  src/types/pblist.ts
  src/utils/cookies.ts
  src/utils/useIntersectionObserver.ts
  yarn.lock
Labels: 💫 feat, ♻️ refactor

#120 비밀번호 찾기 모달 및 기능 구현
  src/components/common/DoubleInputForm.tsx
  src/components/common/ResetPasswordForm.tsx
  src/components/joinPage/common/SetPasswordForm.tsx
  src/hooks/useLogin.ts
  src/hooks/usePasswordAuthentication.ts
  src/hooks/useResetPassword.ts
Labels: 💫 feat, 🟦 typescript

#122 PB 회원가입 UI 및 API 구현
  public/assets/images/arrayBackGray.svg
  public/assets/images/dropDown.svg
  public/assets/images/iconEdit.svg
  public/assets/images/iconMail.svg
  public/assets/images/iconMatching.svg
  public/assets/images/polygon.svg
  public/assets/images/search.svg
  src/app/apis/services/auth.ts
  src/app/findEmail/[...slug]/page.tsx
  src/app/findPassword/[...slug]/page.tsx
  src/app/globals.css
  src/app/join/pb/[slug]/page.tsx
  src/app/join/user/[slug]/page.tsx
  src/app/login/[slug]/page.tsx
  src/components/findPasswordPage/SelectInformation.tsx
  src/components/joinPage/common/AgreeProvision.tsx
  src/components/joinPage/common/DetailProvision.tsx
  src/components/joinPage/common/JoinInformation.tsx
  src/components/joinPage/common/ProvisionContent.tsx
  src/components/joinPage/pb/EnterCareer.tsx
  src/components/joinPage/pb/ModalCompanyList.tsx
  src/components/joinPage/pb/ModalCompanyLocation.tsx
  src/components/joinPage/pb/PBJoinGuide.tsx
  src/components/joinPage/pb/PbComplete.tsx
  src/components/joinPage/pb/RegisterBusinessCard.tsx
  src/components/joinPage/pb/SelectCompany.tsx
  src/components/loginPage/ButtonToAccountSetting.tsx
  src/constants/provisions/pb/PbPersonalInformation.tsx
  src/constants/provisions/pb/PbSysmetic.tsx
  src/constants/provisions/pb/PbThirdParty.tsx
  src/constants/provisions/user/UserPersonalInformation.tsx
  src/constants/provisions/user/UserSysmetic.tsx
  src/constants/provisions/user/UserThirdParty.tsx
  src/hooks/useGetCompanyList.ts
  src/hooks/useGetCompanyLocation.ts
  src/hooks/useLogin.ts
  src/hooks/usePBJoin.ts
  src/hooks/useUserJoin.ts
  src/store/joinStore.ts
  src/store/userStore.ts
  src/types/join.ts
Labels: 💫 feat, 🧑🏻‍🎨 UI, 🟦 typescript, ⚙️ chore

#124 메인페이지, 위치 검색 페이지 로직 구현 및 스타일링
  public/assets/images/chart.svg
  public/assets/images/logo.png
  public/assets/images/myLocation.svg
  public/assets/images/plus.svg
  src/app/apis/services/location.ts
  src/app/globals.css
  src/app/page.tsx
  src/components/common/Card/CardItem/ContentCardItem.tsx
  src/components/common/Navbar.tsx
  src/components/common/TopNav.tsx
  src/components/mainPage/CarouselBanner.tsx
  src/components/mainPage/CustomListSection.tsx
  src/components/mainPage/PbListSection.tsx
  src/components/mainPage/SearchLocation.tsx
  src/components/mainPage/SelectLocationModal.tsx
  src/components/mainPage/SpecialtySection.tsx
  src/components/mainPage/StockFirmSection.tsx
  src/hooks/useGeoLacation.tsx
  src/store/location.ts
  src/styles/carousel.css
  src/styles/specialty.css
  src/types/location.ts
Labels: 💫 feat, 🧑🏻‍🎨 UI, 🟦 typescript

#125 투자성향 분석 API 연결
  public/assets/images/editIcon.svg
  src/app/analysis/page.tsx
  src/app/apis/services/user.ts
  src/components/analysisPage/QuestionSection.tsx
  src/hooks/useCheckPropensity.ts
  src/types/analysis.ts
  src/utils/convertAnswer.ts
Labels: 💫 feat

#131 북마크 페이지 작업, #128 pr에 대한 수정 사항 반영
  src/app/apis/axios.ts
  src/app/apis/services/common.ts
  src/app/apis/services/user.ts
  src/app/bookmark/content/page.tsx
  src/app/bookmark/pb/page.tsx
  src/app/detail/content/page.tsx
  src/app/lounge/hot/page.tsx
  src/app/lounge/new/page.tsx
  src/app/lounge/page.tsx
  src/app/pblist/page.tsx
  src/app/pblist/recommend/page.tsx
  src/components/common/Card/CardItem/ContentCardItem.tsx
  src/components/common/Card/CardList/ContentCardList.tsx
  src/components/common/Card/CardList/PbCardList.tsx
  src/components/loungePage/Content.tsx
  src/components/loungePage/Intro.tsx
  src/components/loungePage/PbRecommend.tsx
  src/components/pbdetailPage/About.tsx
  src/types/card.ts
  src/types/common.ts
  src/types/contents.ts
  src/types/pb.ts
Labels: 💫 feat, 🟦 typescript

#135 상담 예약 페이지 API 연결 및 리팩토링
  src/app/apis/services/user.ts
  src/app/globals.css
  src/app/management/changeReservation/[slug]/page.tsx
  src/app/reservation/complete/page.tsx
  src/app/reservation/page.tsx
  src/components/managementPage/changeReservationPage/TimeModal.tsx
  src/components/reservationPage/BubbleSection.tsx
  src/components/reservationPage/Modals/CandidateTime.tsx
  src/components/reservationPage/Modals/EditProfileModal.tsx
  src/components/reservationPage/Modals/ForwardingModal.tsx
  src/components/reservationPage/Questions/CheckInfoQuestion.tsx
  src/components/reservationPage/Questions/CheckMemoQuestion.tsx
  src/components/reservationPage/Questions/CommonQuestion.tsx
  src/components/reservationPage/Questions/LocationQuestion.tsx
  src/components/reservationPage/Questions/PurposeQuestion.tsx
  src/components/reservationPage/Questions/TimeSelectQuestion.tsx
  src/components/reservationPage/Questions/TypeQuestion.tsx
  src/components/reservationPage/ReservationChat.tsx
  src/components/reservationPage/SelectTimeModal.tsx
  src/components/reservationPage/TimeSelect.tsx
  src/components/reservationPage/UserBubble/UserBubble.tsx
  src/hooks/useGetReservationPageData.ts
  src/hooks/useLogout.ts
  src/hooks/useSetQuestions.ts
  src/middleware.ts
  src/store/reservationStore.ts
  src/types/analysis.ts
  src/types/management.ts
  src/types/reservation.ts
  src/utils/convertAnswer.ts
  src/utils/timeSelectOptions.ts
Labels: 💫 feat, ♻️ refactor

#138 마이페이지 API 연결 작업
  src/app/apis/services/etc.ts
  src/app/my/editInfo/[slug]/page.tsx
  src/app/my/editInfo/page.tsx
  src/app/my/page.tsx
  src/app/my/propensity/page.tsx
  src/components/common/ResetPasswordForm.tsx
  src/components/myPage/editInfoPage/EditInfoForm.tsx
  src/components/myPage/propensityPage/HydratePropensity.tsx
  src/components/myPage/propensityPage/PropensityChart.tsx
  src/hooks/useMyPageCheck.ts
  src/types/common.ts
Labels: 🐛 bug, 💫 feat

#139 PB리스트 페이지 API 연결
  next.config.js
  public/assets/images/highlight.svg
  src/app/analysis/complete/page.tsx
  src/app/analysis/page.tsx
  src/app/apis/services/auth.ts
  src/app/apis/services/etc.ts
  src/app/apis/services/user.ts
  src/app/globals.css
  src/app/pblist/page.tsx
  src/app/pblist/recommend/page.tsx
  src/components/analysisPage/QuestionSection.tsx
  src/components/common/ButtonModal.tsx
  src/components/common/Card/CardItem/PbCardItem.tsx
  src/components/common/CompanyList.tsx
  src/components/common/TopNav.tsx
  src/components/pblistPage/FilteredPbCardList.tsx
  src/components/pblistPage/PBMenu.tsx
  src/components/pblistPage/PropensityCard.tsx
  src/components/pblistPage/SortTab.tsx
  src/components/pblistPage/SpecialityList.tsx
  src/components/reservationPage/Questions/CheckInfoQuestion.tsx
  src/components/reservationPage/Questions/CheckMemoQuestion.tsx
  src/components/reservationPage/Questions/LocationQuestion.tsx
  src/components/reservationPage/Questions/PurposeQuestion.tsx
  src/components/reservationPage/Questions/TimeSelectQuestion.tsx
  src/components/reservationPage/Questions/TypeQuestion.tsx
  src/components/reservationPage/ReservationChat.tsx
  src/components/reservationPage/UserBubble/UserBubble.tsx
  src/hooks/useGetFilteredPBList.ts
  src/types/pblist.ts
  src/types/reservation.ts
Labels: 💫 feat, 🧑🏻‍🎨 UI

#142 Fix: 타입스크립트 에러 처리
  src/app/analysis/complete/page.tsx
  src/app/analysis/page.tsx
  src/app/my/editInfo/[slug]/page.tsx
  src/app/pblist/recommend/page.tsx
  src/app/reservation/complete/page.tsx
  src/hooks/useGetReservationPageData.ts
  src/types/reservation.ts
Labels: 🐛 bug, 🟦 typescript

#140 메인페이지 API 연결
  src/app/apis/services/common.ts
  src/app/apis/services/location.ts
  src/app/apis/services/user.ts
  src/components/common/Card/CardItem/ContentCardItem.tsx
  src/components/mainPage/CustomListSection.tsx
  src/components/mainPage/PbListSection.tsx
  src/components/mainPage/SpecialtySection.tsx
  src/components/mainPage/StockFirmSection.tsx
  src/types/main.ts
  src/types/reservation.ts
Labels: 💫 feat, ♻️ refactor, 🧑🏻‍🎨 UI

#144 PB 일정관리 페이지 API 연결, 공통 에러 핸들러
  src/app/ReactQueryProvider.tsx
  src/app/apis/services/pb.ts
  src/app/schedule/changeTime/page.tsx
  src/app/schedule/page.tsx
  src/components/common/ErrorModal.tsx
  src/components/schedulePage/Calendar.tsx
  src/components/schedulePage/ConsultationTimeCard.tsx
  src/components/schedulePage/DayScheduleList.tsx
  src/components/schedulePage/InfoModal.tsx
  src/components/schedulePage/changeTimePage/TimePickerButton.tsx
  src/hooks/useApiError.ts
  src/styles/calendar.css
  src/types/reservation.ts
  src/types/schedule.ts
Labels: 💫 feat, ♻️ refactor

#149 PB 프로필 수정 페이지 API 연결
  next.config.js
  package.json
  public/assets/images/addCircle.svg
  public/assets/images/minusCircle.svg
  src/app/ReactQueryProvider.tsx
  src/app/analysis/page.tsx
  src/app/apis/services/auth.ts
  src/app/apis/services/pb.ts
  src/app/globals.css
  src/app/layout.tsx
  src/app/my/editInfo/[slug]/page.tsx
  src/app/my/editProfile/page.tsx
  src/app/my/page.tsx
  src/app/my/propensity/page.tsx
  src/app/not-found.tsx
  src/components/common/ButtonModal.tsx
  src/components/common/Main.tsx
  src/components/joinPage/pb/ModalCompanyList.tsx
  src/components/joinPage/pb/ModalCompanyLocation.tsx
  src/components/myPage/EditProfilePage/AwardForm.tsx
  src/components/myPage/EditProfilePage/CareerForm.tsx
  src/components/myPage/EditProfilePage/EditProfileForm.tsx
  src/components/myPage/EditProfilePage/SelectSpeciality.tsx
  src/components/myPage/EditProfilePage/formSections/AwardsInput.tsx
  src/components/myPage/EditProfilePage/formSections/CareerInput.tsx
  src/components/myPage/EditProfilePage/formSections/CareersInput.tsx
  src/components/myPage/EditProfilePage/formSections/CompanyInput.tsx
  src/components/myPage/EditProfilePage/formSections/FigureInput.tsx
  src/components/myPage/EditProfilePage/formSections/IntroInput.tsx
  src/components/myPage/EditProfilePage/formSections/MsgInput.tsx
  src/components/myPage/EditProfilePage/formSections/PortfolioInput.tsx
  src/components/myPage/EditProfilePage/formSections/ProfileInput.tsx
  src/components/myPage/EditProfilePage/formSections/SpecialityInput.tsx
  src/components/myPage/PBInfo.tsx
  src/components/myPage/editInfoPage/EditInfoForm.tsx
  src/components/myPage/editInfoPage/UserInfoList.tsx
  src/components/myPage/serviceCenterPage/AccordianList.tsx
  src/components/reservationPage/ModalLayout.tsx
  src/hooks/useCheckPropensity.ts
  src/hooks/useEditProfile.ts
  src/hooks/useLogout.ts
  src/hooks/usePBListQueries.ts
  src/mocks/seon/pbProfile.json
  src/types/editProfile.ts
  src/types/join.ts
  src/types/my.ts
  src/types/reservation.ts
  src/utils/convertEditFormData.ts
  src/utils/editProfilescheme.ts
  src/utils/validateFileSize.ts
  yarn.lock
Labels: 💫 feat, ♻️ refactor, 🟦 typescript

#150 디자인 시안에 맞춘 디자인 수정 및 기능 에러 수정
  src/app/join/pb/[slug]/page.tsx
  src/app/login/[slug]/page.tsx
  src/components/common/DoubleInputForm.tsx
  src/components/common/ResetPasswordForm.tsx
  src/components/common/TopNav.tsx
  src/components/findPasswordPage/Authentication.tsx
  src/components/joinPage/common/JoinInformation.tsx
  src/components/joinPage/common/SetPasswordForm.tsx
  src/components/joinPage/pb/EnterCareer.tsx
  src/components/joinPage/pb/ModalCompanyList.tsx
  src/components/joinPage/pb/ModalCompanyLocation.tsx
  src/components/joinPage/pb/RegisterBusinessCard.tsx
  src/components/loginPage/AdminAuthentication.tsx
  src/components/loginPage/KeepLoginButton.tsx
  src/components/myPage/editInfoPage/CheckPassword.tsx
  src/components/myPage/editInfoPage/EditInfoForm.tsx
  src/components/reservationPage/Modals/EditProfileModal.tsx
  src/constants/yupSchema.ts
  src/hooks/useFindEmail.ts
  src/hooks/useLogin.ts
  src/hooks/usePasswordAuthentication.ts
  src/types/login.ts
Labels: 💫 feat, ♻️ refactor

#151 고객관리, 신규예약, 확정된 예약, 예약 변경, 완료된 상담, 취소된 상담 페이지 API 연결
  src/app/ReactQueryProvider.tsx
  src/app/apis/services/pb.ts
  src/app/management/canceledConsultation/[slug]/page.tsx
  src/app/management/changeReservation/[slug]/page.tsx
  src/app/management/completedConsultation/[slug]/page.tsx
  src/app/management/confirmedReservation/[slug]/page.tsx
  src/app/management/newReservation/[slug]/page.tsx
  src/app/management/page.tsx
  src/app/myCounseling/canceledConsultation/[slug]/page.tsx
  src/app/myCounseling/completedConsultation/[slug]/page.tsx
  src/app/myCounseling/newReservation/[slug]/page.tsx
  src/app/myCounseling/page.tsx
  src/app/schedule/changeTime/page.tsx
  src/app/schedule/page.tsx
  src/components/common/ButtonModal.tsx
  src/components/common/Card/CardItem/UserReservationItem.tsx
  src/components/common/ConsultationNoteSection.tsx
  src/components/common/ConsultationScheduleSection.tsx
  src/components/common/ErrorModal.tsx
  src/components/common/ProcessList.tsx
  src/components/common/SingleButton.tsx
  src/components/mainPage/PbListSection.tsx
  src/components/managementPage/ConsultationStatus.tsx
  src/components/managementPage/changeReservationPage/CalendarModal.tsx
  src/components/managementPage/changeReservationPage/ScheduleSection.tsx
  src/components/managementPage/changeReservationPage/TimeModal.tsx
  src/hooks/useApiError.ts
  src/hooks/useGetReservationInfo.ts
  src/hooks/useGetUserInfo.ts
  src/types/management.ts
  src/types/pb.ts
Labels: 💫 feat, ♻️ refactor, 🧑🏻‍🎨 UI, ✅ test

#153 스켈레톤 UI, 404페이지, EditProfile 버그 수정
  src/app/globals.css
  src/app/my/page.tsx
  src/app/not-found.tsx
  src/app/pblist/page.tsx
  src/app/pblist/recommend/page.tsx
  src/components/common/Card/CardItem/PBCardSkeletonItem.tsx
  src/components/common/Card/CardList/PbCardList.tsx
  src/components/myPage/EditProfilePage/EditProfileForm.tsx
  src/components/myPage/EditProfilePage/formSections/CompanyInput.tsx
  src/components/myPage/EditProfilePage/formSections/FigureInput.tsx
  src/components/myPage/EditProfilePage/formSections/IntroInput.tsx
  src/components/myPage/EditProfilePage/formSections/MsgInput.tsx
  src/components/myPage/PBInfo.tsx
  src/components/myPage/serviceCenterPage/AccordianItem.tsx
  src/components/myPage/serviceCenterPage/AccordianList.tsx
  src/components/pblistPage/FilteredPbCardList.tsx
  src/components/pblistPage/PBMenu.tsx
  src/hooks/useEditProfile.ts
  src/hooks/useGetFilteredPBList.ts
  src/hooks/useMyPageCheck.ts
  src/types/editProfile.ts
  src/utils/cookies.ts
Labels: 🐛 bug, 💫 feat, 🧑🏻‍🎨 UI

#154 디자인 수정 및 TopNav 로그아웃 추가
  src/app/globals.css
  src/components/common/DoubleInputForm.tsx
  src/components/common/ResetPasswordForm.tsx
  src/components/common/TopNav.tsx
  src/components/joinPage/common/SetPasswordForm.tsx
Labels: 💫 feat, 🧑🏻‍🎨 UI, 🟦 typescript

#157 로그인 및 이메일/비밀번호 찾기 API 에러 구현
  src/app/apis/axios.ts
  src/app/apis/services/pb.ts
  src/app/join/pb/[slug]/page.tsx
  src/app/join/user/[slug]/page.tsx
  src/app/login/[slug]/page.tsx
  src/app/management/newReservation/[slug]/page.tsx
  src/app/management/page.tsx
  src/app/myCounseling/myReview/[slug]/page.tsx
  src/app/myCounseling/reviewWrite/[slug]/page.tsx
  src/components/Test.tsx
  src/components/common/DoubleInputForm.tsx
  src/components/common/TopNav.tsx
  src/components/findEmailPage/InformationCheck.tsx
  src/components/findEmailPage/InformationItem.tsx
  src/components/joinPage/pb/ModalCompanyList.tsx
  src/components/joinPage/pb/RegisterBusinessCard.tsx
  src/components/joinPage/pb/SelectCompany.tsx
  src/components/mainPage/SearchLocation.tsx
  src/hooks/useAuthentication.ts
  src/hooks/useFindEmail.ts
  src/hooks/useLogin.ts
  src/hooks/usePBJoin.ts
  src/hooks/usePasswordAuthentication.ts
  src/hooks/useResetPassword.ts
  src/hooks/useUserJoin.ts
  src/hooks/useWithdraw.ts
  src/store/userStore.ts
  src/types/common.ts
  src/types/login.ts
Labels: 💫 feat, 🟦 typescript

#158 메인페이지 API 연결 및 코드 수정
  next.config.js
  src/app/myCounseling/reviewWrite/[slug]/page.tsx
  src/app/page.tsx
  src/components/common/Card/CardItem/ContentCardItem.tsx
  src/components/common/Navbar.tsx
  src/components/mainPage/AdminButtonSection.tsx
  src/components/mainPage/CustomListSection.tsx
  src/components/mainPage/PbListSection.tsx
  src/components/mainPage/StockFirmSection.tsx
Labels: 💫 feat, ♻️ refactor

#160 콘텐츠 상세 페이지 api연결, 타입 설정, 댓글수정, 대댓글 수정, 댓글 삭제, 대댓글 삭제, 대댓글 추가, 댓글 추가, 검색 페이지
  public/assets/images/icon/delete.svg
  public/assets/images/icon/edit.svg
  public/assets/images/icon/search_active.svg
  src/app/apis/services/auth.ts
  src/app/apis/services/common.ts
  src/app/apis/services/pb.ts
  src/app/apis/services/user.ts
  src/app/bookmark/content/page.tsx
  src/app/bookmark/pb/page.tsx
  src/app/contents/[slug]/page.tsx
  src/app/contents/edit/page.tsx
  src/app/contents/temporary/[slug]/page.tsx
  src/app/contents/write/page.tsx
  src/app/detail/content/[slug]/page.tsx
  src/app/detail/info/[slug]/page.tsx
  src/app/lounge/hot/page.tsx
  src/app/lounge/new/page.tsx
  src/app/lounge/page.tsx
  src/app/lounge/search/page.tsx
  src/components/common/Card/CardItem/ContentCardItem.tsx
  src/components/common/Card/CardItem/PbCardItem.tsx
  src/components/common/Card/CardList/ContentCardList.tsx
  src/components/common/Card/CardList/PbCardList.tsx
  src/components/contentsPage/Comments.tsx
  src/components/contentsPage/Content.tsx
  src/components/contentsPage/Poster.tsx
  src/components/contentsPage/TemporaryItem.tsx
  src/components/contentsPage/TemporaryList.tsx
  src/components/contentsPage/TemporaryPage/TemporaryItem.tsx
  src/components/contentsPage/TemporaryPage/TemporaryList.tsx
  src/components/contentsPage/Write.tsx
  src/components/contentsPage/WritePage/Write.tsx
  src/components/loungePage/Content.tsx
  src/components/loungePage/SearchPage/ContentsItem.tsx
  src/components/loungePage/SearchPage/ContentsList.tsx
  src/components/loungePage/SearchPage/PbItem.tsx
  src/components/loungePage/SearchPage/PbList.tsx
  src/components/loungePage/SearchPage/SearchFilter.tsx
  src/components/pbdetailPage/About.tsx
  src/components/pbdetailPage/Content.tsx
  src/components/pbdetailPage/Intro.tsx
  src/components/pbdetailPage/pbreviewPage/PbReviewList.tsx
  src/components/searchPage/ContentResult.tsx
  src/components/searchPage/PbResult.tsx
  src/components/searchPage/Search.tsx
  src/hooks/useContentBookMark.ts
  src/hooks/useDelete.ts
  src/styles/content.css
  src/styles/pb.css
  src/types/contents.ts
  src/types/pb.ts
  src/utils/pbMyId.ts
Labels: 💫 feat

#162 버그 처리 및 리팩토링 진행
  src/app/apis/axios.ts
  src/app/apis/services/auth.ts
  src/app/apis/services/etc.ts
  src/app/my/terms/page.tsx
  src/app/reservation/page.tsx
  src/components/analysisPage/QuestionSection.tsx
  src/components/myPage/editInfoPage/CheckPassword.tsx
  src/components/myPage/editInfoPage/EditInfoForm.tsx
  src/components/myPage/serviceCenterPage/AccordianItem.tsx
  src/components/reservationPage/Questions/CheckInfoQuestion.tsx
  src/components/reservationPage/Questions/CheckMemoQuestion.tsx
  src/components/reservationPage/Questions/LocationQuestion.tsx
  src/components/reservationPage/Questions/TimeSelectQuestion.tsx
  src/components/reservationPage/Questions/TypeQuestion.tsx
  src/components/reservationPage/UserBubble/UserBubble.tsx
  src/constants/yupSchema.ts
  src/hooks/useMyPageCheck.ts
  src/hooks/useSetQuestions.ts
  src/utils/timeSelectOptions.ts
Labels: 🐛 bug, ♻️ refactor

#164 임시저장 목록, 임시저장 데이터 불러오기
  src/app/apis/services/pb.ts
  src/app/contents/edit/[slug]/page.tsx
  src/app/contents/edit/page.tsx
  src/app/contents/temporary/[slug]/page.tsx
  src/app/contents/temporary/page.tsx
  src/app/contents/write/page.tsx
  src/app/detail/content/[slug]/page.tsx
  src/app/detail/info/[slug]/page.tsx
  src/app/lounge/page.tsx
  src/components/common/Card/CardItem/ContentCardItem.tsx
  src/components/common/Card/CardItem/PbCardItem.tsx
  src/components/contentsPage/Comments.tsx
  src/components/contentsPage/Content.tsx
  src/components/contentsPage/TemporaryItem.tsx
  src/components/contentsPage/TemporaryList.tsx
  src/components/contentsPage/Write.tsx
  src/components/loungePage/Intro.tsx
  src/components/pbdetailPage/About.tsx
  src/components/pbdetailPage/Content.tsx
  src/components/pbdetailPage/Intro.tsx
  src/components/pbdetailPage/pbreviewPage/PbReviewItem.tsx
  src/hooks/useShare.ts
  src/styles/pb.css
  src/types/contents.ts
  src/types/pb.ts
  src/utils/timeShow.ts
  src/utils/truncateContent.ts
Labels: 💫 feat

#166 QA 버그 수정 및 로그인 API 변경
  package.json
  src/app/apis/services/auth.ts
  src/components/common/DoubleInputForm.tsx
  src/components/joinPage/common/DetailProvision.tsx
  src/components/joinPage/pb/EnterCareer.tsx
  src/components/joinPage/pb/ModalCompanyList.tsx
  src/components/loginPage/KeepLoginButton.tsx
  src/constants/yupSchema.ts
  src/hooks/useUserJoin.ts
  src/types/login.ts
  yarn.lock
Labels: 🐛 bug, 💫 feat, ♻️ refactor

#168 메인페이지 QA Error 코드 수정
  src/app/apis/services/auth.ts
  src/app/management/page.tsx
  src/app/schedule/changeTime/page.tsx
  src/app/schedule/page.tsx
  src/components/common/Navbar.tsx
  src/components/common/TopNav.tsx
  src/components/mainPage/PbListSection.tsx
  src/hooks/useGetUserInfo.ts
Labels: 🐛 bug, ♻️ refactor

#170 투자성향 분석, PB 리스트, 마이페이지 에러 해결
  src/app/analysis/complete/page.tsx
  src/app/my/editInfo/[slug]/page.tsx
  src/app/pblist/recommend/page.tsx
  src/components/common/Card/CardList/PbCardList.tsx
  src/components/common/CompanyList.tsx
  src/components/myPage/BookmarkPreviewCard.tsx
  src/components/myPage/UserInfo.tsx
  src/constants/stepProgressList.ts
  src/hooks/useApiError.ts
  src/hooks/useCheckPropensity.ts
  src/hooks/useGetFilteredPBList.ts
  src/hooks/useMyPageCheck.ts
  src/styles/calendar.css
  src/styles/companyCarousel.css
  src/types/my.ts
Labels: 🐛 bug

#172 Provision
  src/components/joinPage/pb/ModalCompanyList.tsx
Labels: 🐛 bug

#174 페이지에 따른 북마크 유무, 북마크 커스텀 훅, 삭제 커스텀 훅, 북마크 api, 조건부 렌더링
  src/app/apis/services/common.ts
  src/app/apis/services/pb.ts
  src/app/apis/services/user.ts
  src/app/bookmark/content/page.tsx
  src/app/bookmark/pb/page.tsx
  src/app/detail/content/[slug]/page.tsx
  src/app/detail/info/[slug]/page.tsx
  src/app/lounge/hot/page.tsx
  src/app/lounge/new/page.tsx
  src/app/pblist/recommend/page.tsx
  src/components/common/Card/CardItem/ContentCardItem.tsx
  src/components/common/Card/CardItem/PbCardItem.tsx
  src/components/common/Card/CardList/ContentCardList.tsx
  src/components/common/Card/CardList/PbCardList.tsx
  src/components/contentsPage/Content.tsx
  src/components/loungePage/Content.tsx
  src/components/mainPage/CustomListSection.tsx
  src/components/myPage/propensityPage/RecommendPBList.tsx
  src/components/pbdetailPage/About.tsx
  src/components/pbdetailPage/Content.tsx
  src/components/pbdetailPage/Intro.tsx
  src/components/pblistPage/FilteredPbCardList.tsx
  src/components/searchPage/ContentResult.tsx
  src/components/searchPage/PbResult.tsx
  src/hooks/useContentBookMark.ts
  src/hooks/useDelete.ts
  src/hooks/usePbBookMark.ts
  src/types/card.ts
  src/utils/truncateContent.ts
Labels: 💫 feat

#175 배포 에러 테스트
  src/components/joinPage/pb/ModalCompanyList.tsx
Labels: 🐛 bug

#176 Metadata (favicon, sitemap, title) 세팅
  public/assets/favicons/.gitkeep
  public/assets/favicons/android-icon-144x144.png
  public/assets/favicons/android-icon-192x192.png
  public/assets/favicons/android-icon-36x36.png
  public/assets/favicons/android-icon-48x48.png
  public/assets/favicons/android-icon-72x72.png
  public/assets/favicons/android-icon-96x96.png
  public/assets/favicons/apple-icon-114x114.png
  public/assets/favicons/apple-icon-120x120.png
  public/assets/favicons/apple-icon-144x144.png
  public/assets/favicons/apple-icon-152x152.png
  public/assets/favicons/apple-icon-180x180.png
  public/assets/favicons/apple-icon-57x57.png
  public/assets/favicons/apple-icon-60x60.png
  public/assets/favicons/apple-icon-72x72.png
  public/assets/favicons/apple-icon-76x76.png
  public/assets/favicons/apple-icon-precomposed.png
  public/assets/favicons/apple-icon.png
  public/assets/favicons/browserconfig.xml
  public/assets/favicons/favicon-16x16.png
  public/assets/favicons/favicon-32x32.png
  public/assets/favicons/favicon-96x96.png
  public/assets/favicons/favicon.ico
  public/assets/favicons/ms-icon-144x144.png
  public/assets/favicons/ms-icon-150x150.png
  public/assets/favicons/ms-icon-310x310.png
  public/assets/favicons/ms-icon-70x70.png
  src/app/analysis/layout.tsx
  src/app/analysis/page.tsx
  src/app/bookmark/content/layout.tsx
  src/app/bookmark/pb/layout.tsx
  src/app/contents/[slug]/layout.tsx
  src/app/contents/edit/[slug]/layout.tsx
  src/app/contents/temporary/layout.tsx
  src/app/contents/write/page.tsx
  src/app/favicon.ico
  src/app/layout.tsx
  src/app/my/editInfo/layout.tsx
  src/app/my/editProfile/layout.tsx
  src/app/my/faq/page.tsx
  src/app/my/layout.tsx
  src/app/my/notice/page.tsx
  src/app/my/propensity/layout.tsx
  src/app/my/terms/page.tsx
  src/app/pblist/layout.tsx
  src/app/pblist/recommend/layout.tsx
  src/app/reservation/complete/layout.tsx
  src/app/reservation/layout.tsx
  src/app/sitemap.ts
  src/app/withdraw/layout.tsx
Labels: 💫 feat

#177 메인페이지 QA Error 코드 수정
  src/app/ReactQueryProvider.tsx
  src/components/common/Modal/BlurModal.tsx
  src/components/common/Navbar.tsx
  src/components/mainPage/CarouselBanner.tsx
  src/components/pbdetailPage/Profile.tsx
  src/constants/common.ts
  src/hooks/useGetUserInfo.ts
Labels: 🐛 bug, 💫 feat

#179 회원탈퇴 시 Error 코드 수정
  src/hooks/useWithdraw.ts
Labels: 🐛 bug

#180 투자성향 페이지로 이동할 때 마이페이지로 리다이렉트 되는 에러 수정
  src/app/my/propensity/page.tsx
Labels: 🐛 bug

#181 투자성향 페이지, 상담예약 페이지 이탈 후 재접속 시 store 처리
  src/app/analysis/page.tsx
  src/app/my/editInfo/layout.tsx
  src/hooks/useGetReservationPageData.ts
Labels: 🐛 bug

#183 투자자 나의상담, PB 고객관리, 일정관리 페이지 메타데이터 설정
  src/app/management/canceledConsultation/[slug]/page.tsx
  src/app/management/canceledConsultation/layout.tsx
  src/app/management/changeReservation/[slug]/page.tsx
  src/app/management/changeReservation/layout.tsx
  src/app/management/completedConsultation/[slug]/page.tsx
  src/app/management/completedConsultation/layout.tsx
  src/app/management/confirmedReservation/[slug]/page.tsx
  src/app/management/confirmedReservation/layout.tsx
  src/app/management/layout.tsx
  src/app/management/newReservation/[slug]/page.tsx
  src/app/management/newReservation/layout.tsx
  src/app/management/page.tsx
  src/app/myCounseling/canceledConsultation/layout.tsx
  src/app/myCounseling/completedConsultation/layout.tsx
  src/app/myCounseling/confirmedReservation/[slug]/page.tsx
  src/app/myCounseling/confirmedReservation/layout.tsx
  src/app/myCounseling/layout.tsx
  src/app/myCounseling/myReview/layout.tsx
  src/app/myCounseling/newReservation/[slug]/page.tsx
  src/app/myCounseling/newReservation/layout.tsx
  src/app/myCounseling/page.tsx
  src/app/myCounseling/reviewWrite/layout.tsx
  src/app/schedule/changeTime/layout.tsx
  src/app/schedule/layout.tsx
  src/components/common/Card/CardItem/UserReservationItem.tsx
  src/components/common/TopNav.tsx
  src/components/common/UserConsultationStatus.tsx
  src/components/pbdetailPage/Intro.tsx
  src/components/schedulePage/changeTimePage/TimePickerButton.tsx
Labels: 💫 feat, ♻️ refactor

#184 QA 오류 수정
  src/app/my/terms/page.tsx
  src/components/common/Main.tsx
  src/components/common/TopNav.tsx
  src/components/joinPage/common/AgreeProvision.tsx
  src/components/joinPage/common/DetailProvision.tsx
  src/components/joinPage/pb/ModalCompanyList.tsx
  src/constants/provisions/common/CommonPersonalInformation.tsx
  src/constants/provisions/pb/PbPersonalInformation.tsx
  src/constants/provisions/pb/PbSysmetic.tsx
  src/constants/provisions/pb/PbThirdParty.tsx
  src/constants/provisions/user/UserPersonalInformation.tsx
  src/constants/provisions/user/UserSysmetic.tsx
  src/constants/provisions/user/UserThirdParty.tsx
  src/hooks/usePBJoin.ts
  src/hooks/useUserJoin.ts
  src/types/join.ts
Labels: 🐛 bug, ♻️ refactor, 🧑🏻‍🎨 UI

#186 상담예약 페이지, 로그아웃 QA Error 수정
  src/app/apis/axios.ts
  src/app/apis/services/auth.ts
  src/components/common/Main.tsx
  src/components/loginPage/KeepLoginButton.tsx
  src/components/loungePage/Content.tsx
  src/components/myPage/EditProfilePage/formSections/IntroInput.tsx
  src/components/myPage/EditProfilePage/formSections/MsgInput.tsx
  src/components/myPage/propensityPage/HydratePropensity.tsx
  src/components/reservationPage/Questions/TimeSelectQuestion.tsx
  src/hooks/useApiError.ts
  src/hooks/useMyPageCheck.ts
  src/hooks/useSetQuestions.ts
  src/utils/timeSelectOptions.ts
Labels: 🐛 bug

#187 Cookie 차단 시와 로그인 되어있을때의 redirect 구현
  src/app/join/pb/[slug]/page.tsx
  src/app/join/user/[slug]/page.tsx
  src/app/login/[slug]/page.tsx
  src/app/login/page.tsx
  src/components/common/Navbar.tsx
Labels: 💫 feat, ♻️ refactor

#188 로그인,회원가입 이메일/비밀번호 찾기 메타데이터 설정
  src/app/findEmail/[...slug]/layout.tsx
  src/app/findPassword/[...slug]/layout.tsx
  src/app/join/layout.tsx
  src/app/login/layout.tsx
Labels: 💫 feat

#189 로그인 시 마이페이지 접근 안되는 에러 수정
  src/app/my/page.tsx
  src/app/my/terms/page.tsx
  src/components/common/ResetPasswordForm.tsx
  src/hooks/useLogin.ts
  src/hooks/useMyPageCheck.ts
Labels: 🐛 bug

#194 마이페이지 접근 안되는 문제 해결
  src/app/my/page.tsx
  src/hooks/useMyPageCheck.ts
Labels: 🐛 bug

#192 증권사리스트를 미리 불러와서 props로 전달
  src/components/joinPage/pb/ModalCompanyList.tsx
  src/components/joinPage/pb/SelectCompany.tsx
  src/components/myPage/EditProfilePage/formSections/CompanyInput.tsx
Labels: 🐛 bug

#195 마이페이지 연결 안되는 문제 해결
  src/hooks/useMyPageCheck.ts
Labels: 🐛 bug

#197 마이페이지 리다이렉트 문제 해결, middleware 의존성 삭제
  src/app/my/page.tsx
  src/hooks/useMyPageCheck.ts
  src/middleware.ts
Labels: 🐛 bug

#198 Fix: 마이 페이지 접근 문제 해결
  src/app/my/page.tsx
  src/hooks/useMyPageCheck.ts
Labels: 🐛 bug

#199 인풋 클리어 버튼 추가
  src/components/joinPage/common/JoinInformation.tsx
  src/components/joinPage/pb/PbComplete.tsx
  src/components/joinPage/user/UserComplete.tsx
Labels: ♻️ refactor

#200 Fix: 링크 수정
  src/app/apis/services/common.ts
  src/components/mainPage/PbListSection.tsx
  src/components/mainPage/StockFirmSection.tsx
  src/components/myPage/MyReservationStatus.tsx
Labels: 💫 feat

#201 유저 회원가입 완료 페이지에서는 redirect X
  src/app/join/user/[slug]/page.tsx
Labels: ♻️ refactor

#202 Design: 로고 css 수정
  src/components/common/Card/CardItem/ContentCardItem.tsx
Labels: 💫 feat

#204 Write 컴포넌트 수정
  src/app/apis/services/pb.ts
  src/app/contents/[slug]/page.tsx
  src/app/contents/write/page.tsx
  src/app/detail/info/[slug]/page.tsx
  src/components/common/Card/CardItem/ContentCardItem.tsx
  src/components/contentsPage/Write.tsx
  src/components/pbdetailPage/pbreviewPage/PbReviewList.tsx
Labels: 🐛 bug, 💫 feat
