Repository FINALALT1/money-bridge, pull requests merged in 2023-07, with the labels that each got.

#205 ENV 설정
  .gitignore
  src/app/apis/axios.ts
  src/app/layout.tsx
  src/utils/shareKakao.ts
Labels: ♻️ refactor, ⚙️ chore

#206 파일 이름 변경
  src/components/pbdetailPage/About.tsx
  src/components/pbdetailPage/pbreviewPage/PbReviewItem.tsx
  src/utils/consultStyle.ts
Labels: ⚙️ chore

#207 Docs: 리드미 수정
  README.md
Labels: 📝 docs

#210 next.config.js domain에서 https 삭제
  next.config.js
Labels: 🐛 bug

#211 Axios Timeout 10초로 수정
  src/app/apis/axios.ts
  src/components/common/Main.tsx
Labels: 🐛 bug, ⚙️ chore

#212 KAKAO API beforeInteractive 속성 삭제
  src/app/layout.tsx
Labels: ✅ test

#218 QA 수정사항
  package-lock.json
  src/app/apis/services/auth.ts
  src/app/apis/services/common.ts
  src/app/bookmark/content/page.tsx
  src/app/bookmark/pb/page.tsx
  src/app/contents/[slug]/page.tsx
  src/app/contents/edit/[slug]/page.tsx
  src/app/contents/temporary/page.tsx
  src/app/detail/content/[slug]/page.tsx
  src/app/detail/info/[slug]/page.tsx
  src/app/globals.css
  src/app/lounge/page.tsx
  src/components/common/ButtonModal.tsx
  src/components/common/Card/CardItem/ContentCardItem.tsx
  src/components/common/Card/CardItem/PbCardItem.tsx
  src/components/common/Modal/BlurModal.tsx
  src/components/common/Navbar.tsx
  src/components/contentsPage/Comments.tsx
  src/components/contentsPage/Content.tsx
  src/components/contentsPage/Reply.tsx
  src/components/loungePage/Intro.tsx
  src/components/loungePage/PbRecommend.tsx
  src/components/pbdetailPage/About.tsx
  src/components/pbdetailPage/Content.tsx
  src/components/pbdetailPage/Intro.tsx
  src/components/pbdetailPage/pbreviewPage/PbReviewItem.tsx
  src/components/pbdetailPage/pbreviewPage/PbReviewList.tsx
  src/hooks/useApiError.ts
  src/hooks/useContentBookMark.ts
  src/hooks/useErrorHandler.ts
  src/hooks/usePbBookMark.ts
  src/utils/pbMyId.ts
  yarn.lock
Labels: 🐛 bug, 💫 feat, ♻️ refactor, 🧑🏻‍🎨 UI

#219 QA 버그 및 에러 처리
  src/app/analysis/layout.tsx
  src/app/analysis/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/my/editInfo/[slug]/page.tsx
  src/app/my/editInfo/layout.tsx
  src/app/my/editInfo/page.tsx
  src/app/my/layout.tsx
  src/app/my/page.tsx
  src/app/pblist/layout.tsx
  src/app/pblist/page.tsx
  src/app/pblist/recommend/page.tsx
  src/app/reservation/complete/layout.tsx
  src/app/reservation/complete/page.tsx
  src/app/reservation/layout.tsx
  src/app/reservation/page.tsx
  src/components/common/Card/CardList/PbCardList.tsx
  src/components/common/CompanyList.tsx
  src/components/common/LoadingBg.tsx
  src/components/common/Main.tsx
  src/components/myPage/BookmarkPreviewCard.tsx
  src/components/myPage/EditProfilePage/AwardForm.tsx
  src/components/myPage/EditProfilePage/CareerForm.tsx
  src/components/myPage/EditProfilePage/EditProfileForm.tsx
  src/components/myPage/EditProfilePage/formSections/CareerInput.tsx
  src/components/myPage/EditProfilePage/formSections/CareersInput.tsx
  src/components/myPage/PBInfo.tsx
  src/components/myPage/editInfoPage/UserInfoList.tsx
  src/components/pblistPage/PBMenu.tsx
  src/components/pblistPage/SortTab.tsx
  src/components/reservationPage/ReservationChat.tsx
  src/hooks/useCheckPropensity.ts
  src/hooks/useMyPageCheck.ts
  src/middleware.ts
  src/styles/calendar.css
  src/styles/companyCarousel.css
  src/styles/defaultCarousel.css
  src/styles/selectCalendar.css
  src/types/editProfile.ts
Labels: 🐛 bug, ♻️ refactor

#220 QA 버그 수정
  src/app/apis/services/auth.ts
  src/app/globals.css
  src/app/join/user/[slug]/page.tsx
  src/components/common/DoubleInputForm.tsx
  src/components/common/ResetPasswordForm.tsx
  src/components/common/TopNav.tsx
  src/components/findEmailPage/EnterInformation.tsx
  src/components/findEmailPage/InformationCheck.tsx
  src/components/findPasswordPage/Authentication.tsx
  src/components/findPasswordPage/EnterInformation.tsx
  src/components/findPasswordPage/SelectInformation.tsx
  src/components/joinPage/common/AgreeProvision.tsx
  src/components/joinPage/common/JoinInformation.tsx
  src/components/joinPage/common/SetPasswordForm.tsx
  src/components/joinPage/pb/EnterCareer.tsx
  src/components/joinPage/pb/PbComplete.tsx
  src/components/joinPage/pb/RegisterBusinessCard.tsx
  src/components/joinPage/pb/SelectCompany.tsx
  src/components/loginPage/AdminAuthentication.tsx
  src/components/myPage/editInfoPage/CheckUserEmail.tsx
  src/hooks/useAuthentication.ts
  src/hooks/useFindEmail.ts
  src/hooks/useGetCompanyList.ts
  src/hooks/usePasswordAuthentication.ts
  src/hooks/useResetPassword.ts
  src/hooks/useSetModalContent.ts
  src/store/findPasswordStore.ts
  src/types/common.ts
  src/types/login.ts
Labels: 🐛 bug, 💫 feat, ♻️ refactor, 🟦 typescript

#221 QA 진행 후 나온 에러처리 및 예외처리
  src/app/apis/services/common.ts
  src/app/apis/services/location.ts
  src/app/management/canceledConsultation/[slug]/page.tsx
  src/app/management/changeReservation/[slug]/page.tsx
  src/app/management/completedConsultation/[slug]/page.tsx
  src/app/management/confirmedReservation/[slug]/page.tsx
  src/app/management/newReservation/[slug]/page.tsx
  src/app/management/page.tsx
  src/app/myCounseling/canceledConsultation/[slug]/page.tsx
  src/app/myCounseling/completedConsultation/[slug]/page.tsx
  src/app/myCounseling/confirmedReservation/[slug]/page.tsx
  src/app/myCounseling/newReservation/[slug]/page.tsx
  src/app/myCounseling/page.tsx
  src/components/common/Card/CardItem/UserReservationItem.tsx
  src/components/common/TopNav.tsx
  src/components/mainPage/PbListSection.tsx
  src/components/mainPage/SearchLocation.tsx
  src/components/mainPage/SelectLocationModal.tsx
  src/components/mainPage/StockFirmSection.tsx
  src/components/managementPage/changeReservationPage/CalendarModal.tsx
  src/components/managementPage/changeReservationPage/LocationChangeModal.tsx
  src/components/managementPage/changeReservationPage/TimeModal.tsx
  src/components/pbdetailPage/pbreviewPage/PbReviewList.tsx
  src/hooks/useGetReservationInfo.ts
  src/store/location.ts
  src/styles/calendar.css
  src/types/pb.ts
Labels: 🐛 bug, 💫 feat, ♻️ refactor

#225 QA 버그 수정
  src/components/joinPage/pb/EnterCareer.tsx
  src/components/joinPage/pb/ModalCompanyLocation.tsx
  src/components/joinPage/pb/SelectCompany.tsx
  src/components/myPage/EditProfilePage/formSections/CompanyInput.tsx
  src/components/reservationPage/ModalLayout.tsx
Labels: 💫 feat, ♻️ refactor

#226 에러핸들러, 콘텐츠 수정하기, 북마크 수정
  src/app/apis/services/pb.ts
  src/app/contents/[slug]/page.tsx
  src/app/contents/edit/[slug]/page.tsx
  src/components/common/Card/CardItem/ContentCardItem.tsx
  src/components/common/Card/CardItem/PbCardItem.tsx
  src/components/contentsPage/Comments.tsx
  src/components/contentsPage/Content.tsx
  src/components/contentsPage/Reply.tsx
  src/components/contentsPage/TemporaryItem.tsx
  src/components/contentsPage/TemporaryList.tsx
  src/components/contentsPage/Write.tsx
  src/components/pbdetailPage/PbContentButton.tsx
  src/components/pbdetailPage/pbreviewPage/PbReviewList.tsx
  src/hooks/useContentBookMark.ts
  src/hooks/useErrorHandler.ts
  src/hooks/useErrorShow.ts
  src/hooks/usePbBookMark.ts
  src/types/contents.ts
Labels: 🐛 bug, 💫 feat, ♻️ refactor

#227 모달 z-index 수정
  src/components/managementPage/changeReservationPage/CalendarModal.tsx
  src/components/managementPage/changeReservationPage/TimeModal.tsx
Labels: 🐛 bug

#229 위치 바뀔 때마다 거리순 PB리스트 refetch
  src/app/apis/services/etc.ts
  src/components/pblistPage/FilteredPbCardList.tsx
  src/hooks/useGetFilteredPBList.ts
Labels: 🐛 bug

#230 Fix: 위치지정시 위도, 경도 스토어에 리셋되는 현상 해결
  src/app/apis/services/location.ts
  src/hooks/useGeoLacation.tsx
  src/store/location.ts
Labels: 🐛 bug

#232 PB리스트 첫 렌더링 시 params 적용 안되는 문제 해결
  src/hooks/useGetFilteredPBList.ts
Labels: 🐛 bug

#235 수정사항
  package-lock.json
  package.json
  src/app/contents/[slug]/page.tsx
  src/app/contents/write/page.tsx
  src/app/detail/content/[slug]/page.tsx
  src/app/detail/info/[slug]/page.tsx
  src/app/lounge/search/page.tsx
  src/components/common/Card/CardList/ContentCardList.tsx
  src/components/common/Card/CardList/PbCardList.tsx
  src/components/contentsPage/Comments.tsx
  src/components/contentsPage/Content.tsx
  src/components/contentsPage/Reply.tsx
  src/components/contentsPage/Write.tsx
  src/components/pbdetailPage/About.tsx
  src/components/pbdetailPage/Intro.tsx
  src/components/pbdetailPage/pbreviewPage/PbReviewList.tsx
  src/components/searchPage/ContentResult.tsx
  src/components/searchPage/PbResult.tsx
  src/components/searchPage/Search.tsx
  src/utils/pbMyId.ts
  yarn.lock
Labels: 💫 feat

#240 Feat: API 주소 연결 처리(CORS 에러 우회)
  next.config.js
  src/app/apis/axios.ts
Labels: 💫 feat

#242 수정사항
  src/components/common/Card/CardItem/ContentCardItem.tsx
  src/components/common/Card/CardItem/PbCardItem.tsx
  src/components/contentsPage/Comments.tsx
  src/components/contentsPage/Content.tsx
  src/components/contentsPage/Reply.tsx
  src/components/contentsPage/Write.tsx
  src/components/pbdetailPage/About.tsx
  src/components/pbdetailPage/Intro.tsx
  src/hooks/useContentBookMark.ts
  src/hooks/usePbBookMark.ts
  src/hooks/useReplyDelete.ts
Labels: 🐛 bug, 💫 feat

#244 QA 에러 및 버그 수정
  package.json
  src/app/analysis/page.tsx
  src/app/apis/services/etc.ts
  src/app/contents/[slug]/layout.tsx
  src/app/contents/edit/[slug]/page.tsx
  src/app/faq/page.tsx
  src/app/layout.tsx
  src/app/my/editProfile/layout.tsx
  src/app/my/editProfile/page.tsx
  src/app/my/page.tsx
  src/app/my/propensity/page.tsx
  src/app/notice/page.tsx
  src/app/reservation/complete/page.tsx
  src/app/reservation/page.tsx
  src/app/terms/page.tsx
  src/components/common/Card/CardItem/PbCardItem.tsx
  src/components/common/Carousel/MainCarousel.tsx
  src/components/contentsPage/Comments.tsx
  src/components/contentsPage/Content.tsx
  src/components/contentsPage/ContentEditor.tsx
  src/components/contentsPage/Write.tsx
  src/components/loungePage/Content.tsx
  src/components/myPage/EditProfilePage/EditProfileForm.tsx
  src/components/pblistPage/FilteredPbCardList.tsx
  src/components/reservationPage/ReservationChat.tsx
  src/hooks/useEditProfile.ts
  src/hooks/useGetFilteredPBList.ts
  src/hooks/usePbBookMark.ts
  src/styles/carousel.css
  src/styles/content.css
  src/utils/validateFileSize.ts
  yarn.lock
Labels: 🐛 bug, ♻️ refactor

#246 Footer 컴포넌트 구현
  src/app/layout.tsx
  src/app/management/canceledConsultation/[slug]/page.tsx
  src/app/myCounseling/canceledConsultation/[slug]/page.tsx
  src/components/common/Footer.tsx
Labels: 💫 feat, 🧑🏻‍🎨 UI

#247 경로 url 수정
  src/components/common/Footer.tsx
Labels: 🐛 bug

#248 공지사항, FAQ html 태그 보이는 문제 수정
  src/app/sitemap.ts
  src/components/contentsPage/Write.tsx
  src/components/myPage/serviceCenterPage/AccordianItem.tsx
  src/components/pbdetailPage/Intro.tsx
  src/components/pbdetailPage/Profile.tsx
Labels: 🐛 bug

#252 pb상세, 콘텐츠 수정하기에 대한 수정사항
  src/app/detail/content/[slug]/layout.tsx
  src/app/detail/info/[slug]/layout.tsx
  src/app/detail/review/[slug]/layout.tsx
  src/components/contentsPage/Content.tsx
  src/components/contentsPage/Write.tsx
  src/components/pbdetailPage/Intro.tsx
  src/components/pbdetailPage/PbContentButton.tsx
Labels: 🐛 bug, 💫 feat

#253 Fix: refetchQueries로 수정
  src/hooks/usePbBookMark.ts
Labels: 💫 feat

#254 변경된 어드민 URL에 따른 관리자페이지 버튼 링크 수정
  src/components/mainPage/AdminButtonSection.tsx
  src/components/pblistPage/FilteredPbCardList.tsx
Labels: ♻️ refactor

#255 오픈그래프, 트위터카드, robot.ts 설정
  public/assets/images/money-bridge-banner.png
  src/app/layout.tsx
  src/app/robots.ts
Labels: 💫 feat

#256 Fix: pb리스트 페이지에서도 북마크가 원활하게 사용할수있도록 수정
  src/components/pbdetailPage/Intro.tsx
  src/hooks/usePbBookMark.ts
Labels: 🐛 bug, 💫 feat

#258 오픈그래프 에러 수정
  src/app/layout.tsx
Labels: 🐛 bug

#259 오픈그래프 데이터 추가
  src/app/layout.tsx
Labels: 🐛 bug

#260 트위터, 오픈 그래프 속성 metadata 객체로 이동
  src/app/layout.tsx
Labels: 🐛 bug

#257 Fix: 경로 수정
  src/app/contents/edit/[slug]/page.tsx
  src/components/contentsPage/Write.tsx
Labels: 🐛 bug, 💫 feat

#261 Fix: 본인 여부 확인 수정
  src/app/detail/content/[slug]/page.tsx
  src/components/contentsPage/Content.tsx
Labels: 🐛 bug, 💫 feat

#263 QA 에러 및 버그 수정
  src/app/apis/services/auth.ts
  src/app/globals.css
  src/components/contentsPage/ContentEditor.tsx
  src/components/contentsPage/Reply.tsx
  src/components/contentsPage/Write.tsx
  src/hooks/useLogout.ts
Labels: 🐛 bug

#264 북마크 안되는 문제 수정
  src/components/contentsPage/Content.tsx
  src/components/contentsPage/Write.tsx
  src/components/pbdetailPage/Intro.tsx
  src/hooks/useContentBookMark.ts
  src/hooks/usePbBookMark.ts
Labels: 🐛 bug

#265 로그아웃 관련 에러 수정
  src/components/common/Card/CardItem/ContentCardItem.tsx
  src/components/contentsPage/Content.tsx
  src/hooks/useLogout.ts
Labels: 🐛 bug

#266 QA 에러 및 버그 수정
  src/app/layout.tsx
  src/app/my/editProfile/page.tsx
  src/app/page.tsx
  src/app/privacy/page.tsx
  src/components/myPage/EditProfilePage/EditProfileForm.tsx
  src/constants/topNavOptions.ts
Labels: 🐛 bug, 💫 feat

#268 Geolocation 관련 로직 수정
  src/app/apis/services/location.ts
  src/components/common/Footer.tsx
  src/components/common/TopNav.tsx
  src/components/mainPage/SearchLocation.tsx
  src/components/mainPage/SelectLocationModal.tsx
  src/hooks/useGeoLacation.tsx
  src/store/location.ts
Labels: 🐛 bug, 💫 feat

#273 메타데이터 속성 추가
  src/app/layout.tsx
Labels: 🐛 bug, ⚙️ chore

#275 Fix: metadata 관련 에러 수정
  src/app/layout.tsx
Labels: 🐛 bug

#276 Fix: head 태그 안에 자체적으로 meta 태그 추가
  src/app/layout.tsx
Labels: 🐛 bug

#278 메인페이지가 CSR로 동작되는 에러 수정
  src/app/layout.tsx
  src/app/pblist/layout.tsx
  src/app/pblist/page.tsx
Labels: 🐛 bug

#280 콘텐츠 카드 증권사 로고 사이즈 조절
  src/components/common/Card/CardItem/ContentCardItem.tsx
Labels: 🧑🏻‍🎨 UI

#281 시스메틱 측에서 요구한 문구 추가 및 수정
  src/app/login/page.tsx
  src/components/findPasswordPage/Authentication.tsx
  src/components/joinPage/pb/SelectCompany.tsx
  yarn.lock
Labels: 🧑🏻‍🎨 UI

#282 Suspense 위치 수정
  src/app/layout.tsx
Labels: 🐛 bug

#283 Link 경로 수정
  src/components/common/Modal/BlurModal.tsx
Labels: 🐛 bug

#284 Fix: 북마크 아이콘 변동 안되는 버그 수정
  src/components/common/Card/CardItem/ContentCardItem.tsx
Labels: 🐛 bug

#285 Fix: delete 안되는 버그 수정
  src/hooks/useContentBookMark.ts
Labels: 🐛 bug

#286 로그아웃 에러 문제 수정
  src/app/layout.tsx
  src/hooks/useLogout.ts
Labels: 🐛 bug

#287 Fix: pb페이지에서 북마크 등록/해제 후 정보, 콘텐츠 탭 이동시 반영안되는 버그 수정
  src/components/common/Card/CardItem/PbCardItem.tsx
  src/components/pbdetailPage/Intro.tsx
  src/hooks/usePbBookMark.ts
Labels: 🐛 bug

#288 상담 종료 시간이 새벽을 넘어가는 경우의 경우 처리 및 레이아웃 간격 수정
  src/components/reservationPage/TimeSelect.tsx
  src/components/reservationPage/UserBubble/UserBubble.tsx
  src/utils/timeSelectOptions.ts
Labels: 🐛 bug

#290 Fix: 예약 변경시 시간 지정 예외처리 추가
  src/components/managementPage/changeReservationPage/TimeModal.tsx
Labels: 🐛 bug

#291 Fix: 상담 시간 선택 관련 에러 수정
  src/components/reservationPage/TimeSelect.tsx
  src/utils/timeSelectOptions.ts
Labels: 🐛 bug

#295 PB 프로필 form FromProvider 사용
  src/components/myPage/EditProfilePage/AwardForm.tsx
  src/components/myPage/EditProfilePage/CareerForm.tsx
  src/components/myPage/EditProfilePage/EditProfileForm.tsx
  src/components/myPage/EditProfilePage/formSections/AwardsInput.tsx
  src/components/myPage/EditProfilePage/formSections/CareerInput.tsx
  src/components/myPage/EditProfilePage/formSections/CareersInput.tsx
  src/components/myPage/EditProfilePage/formSections/CompanyInput.tsx
  src/components/myPage/EditProfilePage/formSections/FigureInput.tsx
  src/components/myPage/EditProfilePage/formSections/IntroInput.tsx
  src/components/myPage/EditProfilePage/formSections/MsgInput.tsx
  src/components/myPage/EditProfilePage/formSections/PortfolioInput.tsx
  src/components/myPage/EditProfilePage/formSections/ProfileInput.tsx
  src/types/editProfile.ts
Labels: ♻️ refactor

#296 useIntersectionObserver hooks 폴더로 이동
  src/app/management/page.tsx
  src/app/myCounseling/page.tsx
  src/components/common/Card/CardList/ContentCardList.tsx
  src/components/common/Card/CardList/PbCardList.tsx
  src/components/myPage/serviceCenterPage/AccordianList.tsx
  src/components/pbdetailPage/pbreviewPage/PbReviewList.tsx
  src/components/pblistPage/FilteredPbCardList.tsx
  src/hooks/useIntersectionObserver.ts
Labels: ⚙️ chore
